[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable over-sensitive secrets scanning for public environment variables
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
